k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: bbcd5761-a239-53f8-9b84-87c49d5ec6da
    cluster_name: demo-prod-f0f10329-d19b-4d2f-acb5-6fc49194e0e5
- manifest_path: /manifests
  cluster_info:
    cluster_id: bbcd5761-a239-53f8-9b84-87c49d5ec6da
    cluster_name: demo-prod-f0f10329-d19b-4d2f-acb5-6fc49194e0e5
- manifest_path: /manifests
  cluster_info:
    cluster_id: bbcd5761-a239-53f8-9b84-87c49d5ec6da
    cluster_name: demo-prod-f0f10329-d19b-4d2f-acb5-6fc49194e0e5
